/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: {
          DEFAULT: 'var(--surface)',
          sunken: 'var(--surface-sunken)',
          hover: 'var(--surface-hover)',
        },
        ink: {
          DEFAULT: 'var(--ink)',
          secondary: 'var(--ink-secondary)',
          tertiary: 'var(--ink-tertiary)',
          inverse: 'var(--ink-inverse)',
        },
        border: {
          DEFAULT: 'var(--border)',
          strong: 'var(--border-strong)',
        },
        grid: 'var(--grid)',
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          soft: 'var(--accent-soft)',
          ink: 'var(--accent-ink)',
        },
        profit: {
          DEFAULT: 'var(--profit)',
          soft: 'var(--profit-soft)',
          ink: 'var(--profit-ink)',
        },
        loss: {
          DEFAULT: 'var(--loss)',
          soft: 'var(--loss-soft)',
          ink: 'var(--loss-ink)',
        },
        'neutral-flat': 'var(--neutral-flat)',
        status: {
          pending: 'var(--status-pending)',
          'pending-soft': 'var(--status-pending-soft)',
          running: 'var(--status-running)',
          'running-soft': 'var(--status-running-soft)',
          success: 'var(--status-success)',
          'success-soft': 'var(--status-success-soft)',
          failed: 'var(--status-failed)',
          'failed-soft': 'var(--status-failed-soft)',
          paused: 'var(--status-paused)',
          'paused-soft': 'var(--status-paused-soft)',
          warning: 'var(--status-warning)',
          'warning-soft': 'var(--status-warning-soft)',
        },
        series: {
          1: 'var(--series-1)',
          2: 'var(--series-2)',
          3: 'var(--series-3)',
          4: 'var(--series-4)',
          5: 'var(--series-5)',
          6: 'var(--series-6)',
        },
      },
      fontFamily: {
        ui: ['var(--font-ui)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        display: ['var(--text-display)', { lineHeight: 'var(--lh-display)', letterSpacing: 'var(--tracking-display)' }],
        h1: ['var(--text-h1)', { lineHeight: 'var(--lh-h1)', letterSpacing: 'var(--tracking-h1)' }],
        h2: ['var(--text-h2)', { lineHeight: 'var(--lh-h2)' }],
        h3: ['var(--text-h3)', { lineHeight: 'var(--lh-h3)' }],
        body: ['var(--text-body)', { lineHeight: 'var(--lh-body)' }],
        sm: ['var(--text-sm)', { lineHeight: 'var(--lh-sm)' }],
        xs: ['var(--text-xs)', { lineHeight: 'var(--lh-xs)', letterSpacing: 'var(--tracking-xs)' }],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        lg: 'var(--shadow-lg)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
      },
      screens: {
        sm: '480px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1600px',
      },
      transitionTimingFunction: {
        instrument: 'var(--ease)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        DEFAULT: 'var(--dur)',
        slow: 'var(--dur-slow)',
      },
    },
  },
  plugins: [],
};
